# Generated by Django 4.2.8 on 2024-01-08 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cesfam',
            fields=[
                ('id_cesfam', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de CESFAM')),
            ],
            options={
                'verbose_name_plural': 'Cesfams',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de especialidad')),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50, verbose_name='Nombre del profesional')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.especialidad')),
            ],
            options={
                'verbose_name_plural': 'Profesionales',
            },
        ),
    ]
