# Generated by Django 4.2.8 on 2024-01-08 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name='Nombre de usuario')),
                ('rut', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Ingresa un RUT chileno válido (ej. 21140960-6).', regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUT')),
            ],
        ),
        migrations.RenameField(
            model_name='profesional',
            old_name='nombre_completo',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='profesional',
            name='apellido',
            field=models.CharField(default='Esteban', max_length=50, verbose_name='Apellido del profesional'),
        ),
    ]
