# Generated by Django 4.2.8 on 2024-01-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='inscrito_hs',
            field=models.BooleanField(default=False),
        ),
    ]
