# Generated by Django 4.2.8 on 2024-01-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_reserva_id_reserva_id_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='id_reserva',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
