# Generated by Django 4.2.8 on 2024-01-08 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_paciente_rename_nombre_completo_profesional_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='profesionales_favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritos', to='chatbot.profesional'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Ingresa un RUT chileno válido sin dv (ej. 211409606).', regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido del profesional'),
        ),
    ]
