# Generated by Django 4.2.8 on 2024-01-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_paciente_inscrito_hs'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nombre_completo',
            field=models.CharField(default='Damian', max_length=20, verbose_name='Nombre del paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='inscrito_hs',
            field=models.BooleanField(default=False, verbose_name='Marcar si está inscrito en HoraSalud'),
        ),
    ]
