# Generated by Django 4.2.8 on 2024-01-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_reserva_id_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='Nombre de usuario del profesional')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del profesional')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido del profesional')),
            ],
            options={
                'verbose_name_plural': 'Funcionarios',
            },
        ),
    ]
