# Generated by Django 4.2.8 on 2024-01-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_paciente_nombre_completo_alter_paciente_inscrito_hs'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='archivo_audio',
            field=models.FileField(blank=True, null=True, upload_to='archivos_audio/'),
        ),
    ]
